@monoSecret = {{$dotenv MONO_SECRET}}
@monoApiToken = {{$dotenv MONO_API_TOKEN}}

### 1. Перевірка локального сервера / health-check
GET http://localhost:3000/ping

###

### 2. Тестовий запит до публічного API (для перевірки роботи плагіна)
GET https://jsonplaceholder.typicode.com/posts/1

###

### 3. Імітація вебхуку Monobank на твій сервер
POST http://localhost:3000/monobank/{{monoSecret}}
Content-Type: application/json

{
  "type": "StatementItem",
  "data": {
    "account": "test_account",
    "statementItem": {
      "id": "test_mono_id_12345",
      "time": 1724697600,
      "description": "Тестування вебхуку Monobank",
      "mcc": 5411,
      "originalAmount": -15000,
      "amount": -15000,
      "operationAmount": -15000,
      "currencyCode": 980,
      "commissionRate": 0,
      "cashbackAmount": 0,
      "balance": 500000,
      "hold": false
    }
  }
}

###

### 4. Ручна реєстрація webhook у Monobank API (змінює живе налаштування)
POST https://api.monobank.ua/personal/webhook
X-Token: {{monoApiToken}}
Content-Type: application/json

{
  "webHookUrl": "https://finance-bot-v24m.onrender.com/monobank/{{monoSecret}}"
}

###

### 5. Імітація локального вебхуку Monobank (Захищений маршрут)
POST http://localhost:3000/monobank/{{monoSecret}}
Content-Type: application/json

{
  "type": "StatementItem",
  "data": {
    "account": "test_account",
    "statementItem": {
      "id": "test_mono_id_12345",
      "time": 1724697600,
      "description": "Тестування захищеного вебхуку Monobank",
      "mcc": 5411,
      "originalAmount": -15000,
      "amount": -15000,
      "operationAmount": -15000,
      "currencyCode": 980,
      "commissionRate": 0,
      "cashbackAmount": 0,
      "balance": 500000,
      "hold": false
    }
  }
}
